export default [
  "Agriculture",
  "agriculture",
  "Construction",
  "construction",
  "Attachments",
  "attachments",
  "Tractors",
  "tractors",
  "Combines",
  "combines",
  "Headers",
  "headers",
  "Harvesting",
  "harvesting",
  "Hay & Forge",
  "hay & forge",
  "hay and forge",
  "Hay and Forge",
  "hay & Forge",
  "Hay & forge",
  "Chemical Applicators",
  "chemical applicators",
  "Chemical applicators",
  "chemical Applicators",
  "Seeding & Planting",
  "seeding & planting",
  "seeding and planting",
  "Trailers",
  "trailers",
  "Skid Steers",
  "skid steers",
  "Excavator",
  "excavator",
  "Forklifts",
  "forklifts",
  "Backhoes",
  "backhoes",
  "Accessories",
  "accessories",
  "Trucks",
  "trucks",
  "Flatbed",
  "flatbed",
  "Drop Deck",
  "drop deck",
  "Liquid Tanker",
  "liquid tanker",
  "Grain Trailer",
  "grain trailer",
  "live bottom",
  "Live Bottom",
  "Reefer",
  "reefer",
  "Dry Van",
  "dry van",
  "Belly Dump",
  "belly dump"
];
